### ISSUE TITLE
xz:(stdin): File format not recognized

### ISSUE THREAD

**Issue by sankarsubramanian** [vapor-community/heroku-buildpack#23]
remote: Building source:
remote: 
remote: -----> Swift app detected
remote: -----> Installing clang 5.0.0
remote: xz: (stdin): File format not recognized
remote:  !     Push rejected, failed to compile Swift app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to swift-listener.
remote: 
To https://git.heroku.com/swift-listener.git

**Comment by raheelahmad** [comment]
@sankarsubramanian try switching your heroku stack to `cedar-14`.

**Comment by vzsg** [comment]
Oh, so Heroku made heroku-18 the new default? That'll wreak havoc with Swift for plenty of reasons...

**Comment by raheelahmad** [comment]
Basically, the `clang` script is failing because there isn't a clang release for the new Ubuntus. 

https://devcenter.heroku.com/changelog-items/1485

**Comment by vzsg** [comment]
This is now fixed, the heroku-18 stack is supported out of the box.
