### ISSUE TITLE
swiftenv fails on heroku push

### ISSUE THREAD

**Issue by raheelahmad** [vapor-community/heroku-buildpack#24]
I am wondering why the `UNSET` is set here: https://github.com/vapor-community/heroku-buildpack/blob/master/bin/steps/swiftenv#L3

It ends up failing a push to heroku with:

```
remote: -----> Installing swiftenv
remote: fatal: Not a git repository (or any parent up to mount point /app)
remote: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
remote:  !     Push rejected, failed to compile Swift app.
remote:
```

and removing that line fixes the process.

**Comment by vzsg** [comment]
Can you add some more details? That line is a leftover from the past, I'm not sure about its purpose, but what's more curious is that I've never run into such an issue before.

So, which version of the buildpack are you running (vapor/vapor from the buildpack registry, or directly from GitHub), and what stack?

**Comment by raheelahmad** [comment]
Because of https://github.com/vapor-community/heroku-buildpack/issues/23 I was trying out a custom build pack, this repo's fork: https://github.com/raheelahmad/heroku-buildpack. The only change there is removing this `UNSET`, which made it work for me.

It's on `cedar-14`.

**Comment by vzsg** [comment]
This should now be resolved.
