### ISSUE TITLE
Request: Support Heroku 18 stack

### ISSUE THREAD

**Issue by andrewtheis** [vapor-community/heroku-buildpack#31]
With Swift 4.2, Ubuntu 18 builds [are available](https://swift.org/download/#releases) - which should allow for support of Heroku 18 stack. I assume it's just a matter of detecting the Heroku stack, ensuring the requested Swift version is > 4.2, and then downloading the correct Swift release. I'll see if I can get a PR in for this unless someone else gets to it first.

**Comment by vzsg** [comment]
Your assumption is close, but unfortunately is not enough. The buildpack, as it is now, tries to download `clang` from llvm.org - where 18.04 builds are not available, and we need a different strategy.

I have previously found a working solution: we can install a proper version of `clang` using the [heroku apt buildpack](
https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-apt). The `ext-clang` branch here is compatible with that.

**Comment by vzsg** [comment]
I was thinking of changing the buildpack to work as it previously did on the 14 and 16 stacks, and print new instructions on 18 to set up the other buildpack.

**Comment by scinfu** [comment]
Any news?

**Comment by vzsg** [comment]
Not really. But if you can't wait, here's a working guide:

So assuming you have an already set up project on Heroku (with only the vapor buildpack), do the following:

1. Change the vapor buildpack to use the ext-clang branch, where I have removed the script that installs clang.
    ```bash
    heroku buildpacks:set https://github.com/vapor-community/heroku-buildpack.git#ext-clang
    ```
1. Add the apt buildpack at the first index (executed before the vapor buildpack):
    ```bash
    heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-apt
    ```
1. Create an Aptfile to install a few things:
    ```bash
    cat <<EOF >Aptfile
    clang
    libssl1.0
    libssl1.0-dev
    EOF
    ```
1. Set the active stack to heroku-18:
    ```bash
    heroku stack:set heroku-18
    ```
1. Commit and deploy.
    ```bash
    git commit -am "Add Aptfile"
    git push heroku master
    ```

**Comment by marekpridal** [comment]
@vzsg after upgrading to Heroku 18 using your guideline Vapor app bumped from 10 MB to 115 MB 😅 it's probably caused by installing
```
clang
libssl1.0
libssl1.0-dev
```
using Aptfile 🙂

**Comment by vzsg** [comment]
Hmm. That's bad news. libssl1.0 shouldn't be necessary anymore, but we need to find a way to install clang without it getting into the final slug.

**Comment by vzsg** [comment]
Oh hey, it seems llvm.org now hosts a build of clang for Ubuntu 18.04! I'll play around with it, and if we're lucky, the buildpack can be self-reliant again.
