### ISSUE TITLE
Support Package.swift symlink?

### ISSUE THREAD

**Issue by honghaoz** [vapor-community/heroku-buildpack#34]
Currently, I use a "Package.swift" symbolic link at the root directory instead of a real file. The build pack doesn't handle the symlink case. 

Could we support it? Thanks.

**Comment by tanner0101** [comment]
@honghaoz what is the error you are getting?

**Comment by honghaoz** [comment]
Hey @tanner0101 here is the error log:
```
➜  XXX git:(master) git push heroku master  
Counting objects: 131, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (102/102), done.
Writing objects: 100% (131/131), 69.21 KiB | 4.33 MiB/s, done.
Total 131 (delta 33), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://github.com/vapor-community/heroku-buildpack
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to XXX.
remote: 
To https://git.heroku.com/XXX.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/XXX.git'
```

**Comment by tanner0101** [comment]
I don't know much about Heroku buildpacks, but my guess is the problem is here: https://github.com/vapor-community/heroku-buildpack/blob/master/bin/detect#L4

Seems like we need to expand that check to support symlinks. Maybe this will help: https://stackoverflow.com/questions/5767062/how-to-check-if-a-symlink-exists

**Comment by honghaoz** [comment]
@tanner0101 Yes, I suspect that check doesn't support symlinks. I will do a fork and test with it. If it works, I could put a PR for it.

**Comment by honghaoz** [comment]
I found this error was caused by the symlink's absolute path of the source file.
Specifically,

This was the bad symlink:
```
Package.swift -> <absolute path>/Environment/production/Package.swift
```

After I changed the symlink to 
```
Package.swift -> ./Environment/production/Package.swift
```
The buildpack works well.

Credit to this post: https://www.mokacoding.com/blog/symliks-in-git/
