### ISSUE TITLE
Error while using swift 5

### ISSUE THREAD

**Issue by FlippAre** [vapor-community/heroku-buildpack#37]
Was feeling a bit adventures and set my `.swift-version`-file to `5.0`. The build goes through, but on launch I get the following error

```
heroku[web] notice Starting process with command `Run serve --env production --hostname 0.0.0.0 --port 35944`
heroku[web] notice Process exited with status 127
app[web] error Run: error while loading shared libraries: libicui18nswift.so.61: cannot open shared object file: No such file or directory
```

Using Vapor3 with Postgres and all dependencies bumped to latest versions

**Comment by vzsg** [comment]
Thanks for testing it! Apparently there's a new shared library that the buildpack doesn't yet anticipate. I'll take a look at it during the weekend.

**Comment by vzsg** [comment]
The weekend didn't work out as I hoped, but the fix is now available both directly and via `vapor/vapor`. Thanks @mliberman 👍.
