### ISSUE TITLE
Heroku-22 stack

### ISSUE THREAD

**Issue by wolverian** [vapor-community/heroku-buildpack#70]
Set your stack to `heroku-22` and:

```
remote: -----> Building on the Heroku-22 stack
remote: -----> Using buildpack: vapor/vapor
remote: -----> Swift app detected
remote: -----> Using Swift 5.6 (default)
remote: -----> Using built-in clang (Swift 5.6)
remote: -----> Installing swiftenv
remote: -----> Installing Swift 5.6
remote: We don't have build instructions for 5.6.
remote:  !     Push rejected, failed to compile Swift app.
```

The buildpack works correctly on `heroku-20`.

**Comment by vzsg** [comment]
That's normal at the moment. There is no Swift release that supports Ubuntu 22.04 yet, see [the official page](https://www.swift.org/download/), but I'll update buildpack as soon as we get one.

**Comment by vzsg** [comment]
Let me know if it works via swiftenv but not via the buildpack, I may have some updating to do in the buildpack source.
(There's an old version of swiftenv copied in here as the buildpack registry doesn't support git submodules.)

**Comment by vzsg** [comment]
I'm happy to report that Swift 5.7 is finally released, and it works with the heroku-22 stack.
The buildpack is now updated to support it.
