### ISSUE TITLE
Support Ubuntu 23.10 and 24.04

### ISSUE THREAD

**Issue by MahdiBM** [vapor-community/heroku-buildpack#76]
Not sure how much of a valid "issue" this is, just filing an issue to make sure.
These newer Ubuntu versions are now supported in the Swift releases since Swift 5.10.1, per https://www.swift.org/install/linux/ubuntu/#versions.

**Comment by vzsg** [comment]
Thanks. Heroku has yet to [release a new stack](https://devcenter.heroku.com/articles/stack-update-policy#addition-of-new-stacks) for Ubuntu 24.04, which may take months. But when it happens, the buildpack will be ready, as I added the URLs for 24.04 already :)

(And there won't be 23.10 support, as it's not LTS.)
